/* Public header for libminorminer_clib */

/* Generated by gcc -E -P graph_clib.h local_interaction_clib.h find_embedding_clib.h > minorminer_clib.h */

typedef struct input_graph input_graph;
  input_graph* make_graph();
  void delete_graph(input_graph*);
  void push_back(input_graph*,int,int);
  void clear(input_graph*);
  int num_nodes(input_graph*);
  int num_edges(input_graph*);
  int isCancelled();
  void setCancelled();
  void resetCancelled();
  void displayOutput_clib(const char *msg);
  typedef struct clib_LocalInteraction clib_LocalInteraction;
       
       
  typedef struct vectorint vectorint;
  typedef struct vvi vvi;
  typedef struct mivi mivi;
  vectorint* make_vectorint();
  int vectorint_length(vectorint*);
  int *vectorint_to_arrayint(vectorint*);
  void vectorint_push_back(vectorint*, int);
  void vectorint_print(vectorint*);
  void delete_vectorint(vectorint*);
  vvi* make_vvi();
  int vvi_length(vvi*);
  vectorint* vvi_at(vvi*, int);
  void vvi_push_back(vvi*, vectorint*);
  void vvi_print(vvi*);
  void delete_vvi(vvi*);
  mivi* make_mivi();
  void mivi_set(mivi*, int, vectorint*);
  void mivi_unset(mivi*, int);
  void mivi_map(mivi *, void (*callback)(int, vectorint*));
  void delete_mivi(mivi*);
  typedef struct input_graph input_graph;
  input_graph* make_graph();
  void delete_graph(input_graph*);
  void push_back(input_graph*,int,int);
  void clear(input_graph*);
  int num_nodes(input_graph*);
  int num_edges(input_graph*);
       
  typedef struct optional_parameters_clib {
    int max_no_improvement;
    int timeout;
    int tries;
    int verbose;
    int inner_rounds;
    int max_fill;
    int return_overlap;
    int chainlength_patience;
    int threads;
    int skip_initialization;
    mivi* fixed_chains;
    mivi* initial_chains;
    mivi* restrict_chains;
    int (*cancelled_callback) ();
    void (*display_callback) (const char*);
  } optional_parameters_clib;
  optional_parameters_clib* make_default_optional_parameters( mivi*, mivi*, mivi*);
  void delete_optional_parameters(optional_parameters_clib* o);
  int findembedding_clib(input_graph *, input_graph *, optional_parameters_clib *, vvi*);
